spring:
    application:
        name: keylog


    # DB 설정
    datasource:
        # driver-class-name: oracle.jdbc.driver.OracleDriver > 9i
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@13.125.37.74:1521/xe
        username: springhsw
        password: java1234



server:
    port: 8010

    # XML Mapper Locations
mybatis:
    mapper-locations: classpath:/mapper/*.xml
