spring:
    application:
        name: boot-security

    # DB 설정
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@localhost:1521/xe
        username: springboot
        password: java1234

    #옆에 DB 설정하면 코끼리 위에 DB설정가능

    #JPA 설정
    jpa:
        database: oracle
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #tbl_address 방지
        show-sql: true
        properties:
            hibernate:
                format_sql: true #이쁘게

server:
    port: 8090