spring:
    application:
        name: boot-security-jwt

    # DB 설정
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@localhost:1521/xe
        username: springboot
        password: java1234

    #JPA 설정
    jpa:
        database: oracle
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #tbl_address 방지
        show-sql: true
        properties:
            hibernate:
                format_sql: true #이쁘게

    # 암호화 키
    jwt:
        secret: cf2a2baa65bac5f14806895c5390d44e366c73ffe580f27a1f2228373f7eeec7   #Sha256



server:
    port: 8090